version: "3.8"
services:

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "3000:3000"

  server:
    build: ./server
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    # volumes:
    #   - "./:/usr/server/"
    #   - "/usr/server/node_modules"

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bharg
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
