version: "3.8"
services:
  server:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/server

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bharg
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
